title: "Data Warehousing with PostgreSql Project"
description: "Building a modern data warehouse with postgresql, including ETL processes, data modeling, and analytics"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-seo-tag
